package noppes.npcs.constants;

public enum EnumPacketClient
{
	CHAT, 
	MESSAGE, 
	DIALOG, 
	QUEST_COMPLETION,
	EDIT_NPC, 
	PLAY_SOUND, 
	PLAY_MUSIC, 
	UPDATE_NPC, 
	ROLE, 
	GUI, 
	PARTICLE, 
	DELETE_ENTITY, 
	SCROLL_LIST, 
	SCROLL_DATA, 
	SCROLL_DATA_PART, 
	SCROLL_SELECTED, 
	GUI_DATA, 
	GUI_ERROR, 
	GUI_CLOSE, 
	VILLAGER_LIST, 
	CHATBUBBLE, 
	CLONE, 
	DIALOG_DUMMY, 
	CONFIG, 
	EYE_BLINK, 
	SYNC_ADD, 
	SYNC_END, 
	SYNC_UPDATE, 
	SYNC_REMOVE, 
	MARK_DATA, 
	UPDATE_ITEM, 
	GUI_UPDATE, 
	CHEST_NAME, 
	VISIBLE_FALSE, 
	VISIBLE_TRUE,
	MESSAGE_DATA, // New
	NPC_VISUAL_DATA, // New
	SET_GHOST_RECIPE, // New
	SET_MARCETS, // New
	MARCET_UPDATE, // New
	MARCET_CLOSE, // New
	SCRIPT_DATA, // New
	QUEST_CHOOSE_REWARD, // New
	DETECT_HELD_ITEM, // New
	BORDER_DATA, // New
	BUILDER_SETTING, // New
	SAVE_SCHEMATIC, // New
	GET_SCHEMATIC, // New
	UPDATE_HUD, // New
	DIMENSIOS_IDS, // New
	DROP_GROUP_DATA; // New
	
}
